name: Folder to Branches
run-name: Commit each folder to a dedicated branch
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  folder-to-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List folders
        id: list_folders
        run: |
          ls -d */ | sed 's#/##' > /tmp/slugs.txt
          cat /tmp/slugs.txt

      - name: Process each slug
        run: |
          shopt -s extglob
          mkdir /tmp/working
          mv ** /tmp/working

          ls -la "/tmp/working/hello-world-node"
          
          git config --global user.email "abeisgreat@abeisgreat.com"
          git config --global user.name "Abe's Bot"
  
          while IFS= read -r slug; do
            echo "Processing slug: $slug"
            rm -rf /tmp/repo
            mkdir /tmp/repo
            cd /tmp/repo
            cp -r $GITHUB_WORKSPACE/.git .
          
            git branch "$slug" || git checkout -b "origin/$slug" 
            git fetch
            echo "ls /tmp/working/$slug"
            ls "/tmp/working/$slug"
            cp /tmp/working/$slug/* .
          
            git add .
            git commit -a -m "Sync latest $slug"
            git push --force origin "$slug"
            
          done < /tmp/slugs.txt