name: Folder to Branches
run-name: Commit each folder to a dedicated branch
on:
  push:
    branches:
      - main
jobs:
  folder-to-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List folders
        id: list_folders
        run: |
          ls -d */ | sed 's#/##' > slugs.txt
          cat slugs.txt

      - name: Process each slug
        run: |
          while IFS= read -r slug; do
            echo "Processing slug: slug"
            # Replace the following line with your custom script or command
            # Example: cd "$folder" && npm install && npm test
          done < slugs.txt