name: Folder to Branches
run-name: Commit each folder to a dedicated branch
on:
  push:
    branches:
      - main
jobs:
  folder-to-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List folders
        id: list_folders
        run: |
          ls -d */ | sed 's#/##' > slugs.txt
          cat slugs.txt

      - name: Process each slug
        run: |
          shopt -s extglob
          mkdir .temp
          mv !(.temp) .temp

          while IFS= read -r slug; do
            echo "Processing slug: $slug"
          
            git branch "$slug" || git checkout -b "$slug" 
            ls .temp
            cp -R ".temp/$slug/*" .
          
            git commit -a "Sync latest $slug"
            git push origin "$slug"
            
          done < .temp/slugs.txt